### ISSUE TITLE
Doesn't work with Google Chrome latest version (61.0.3163.91)

### ISSUE THREAD

**Issue by indranilatwork** [zehfernandes/jquery.fullContent#14]
Hi,

Is there any support for this library at this moment? I was using this plugin in one website and it was working. But with the latest chrome update it doesn't work and it's always showing the page which is at left:0px top:0px position.

Can I know, if this issue will be fixed or not?

**Comment by colega** [comment]
It's an issue with the scrollTo library being used, while waiting for my PR to be merged (https://github.com/zehfernandes/jquery.fullContent/pull/15), you can just update your [scrollTo](https://github.com/flesler/jquery.scrollTo) & [jQuery](https://code.jquery.com/jquery-1.12.4.min.js) to latest versions (use the latest 1.x version from jQuery, something didn't work for me with the 3.x)

**Comment by shekhzyaul** [comment]
i updated both the jquery and scrollto plugin but its not working

**Comment by indranilatwork** [comment]
Yeah I realized it's issue with the scrollTo. But even after using the later jQuery it didn't work. For a workaround I used jQuery animate in the library file and it worked for now:
        $('html, body').animate({
            scrollTop: offset.top,
            scrollLeft: offset.left
        }, 500);

**Comment by zehfernandes** [comment]
Thanks @colega to fix it!
